version: '3.5'

networks:
  mg-network:
    external: true
    name: mg-network

services:
  website:
    container_name: website.mg-dashboard
    image: mg-dashboard-website

    ports:
      - 80:80
    networks:
      - mg-network
    
    restart: always

  api:
    container_name: api.mg-dashboard
    image: mg-dashboard-api
    depends_on:
      - database

    ports:
      - 8000:80
      - 8001:443
    networks:
      - mg-network
    restart: always

  mqtt:
    container_name: mqtt.mg-dashboard
    image: mg-dashboard-mqtt
    ports:
      - 1883:1883
      - 8083:8083
    networks:
      - mg-network
    restart: always

  database:
    container_name: db.mg-dashboard
    image: postgres

    working_dir: /home/db
    env_file:
      - ./db/.env
    volumes:
      - ./db/data/persist:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - mg-network
    restart: always

  dbadmin:
    container_name: dbadmin.mg-dashboard
    image: dpage/pgadmin4:latest
    depends_on:
      - database

    env_file:
      - ./db/.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - mg-network
    restart: always

volumes:
    pgadmin-data:  